apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: kubernetes.docker.internal
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: api-service
                port:
                  number: 80
            path: /api(/|$)(.*)
          - pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
            path: /static-frontend(/|$)(.*)
          - pathType: ImplementationSpecific
            backend:
              service:
                name: next-service
                port:
                  number: 80
            path: /()(.*)
